### ISSUE TITLE
transformMixins

### ISSUE THREAD

**Issue by cheshrkat** [happilymarrieddad/puglatizer#2]
This could be pebkac (it's been a long day, the pug site is down and I should probably be taking that as a sign.. ;)) but it looks to me like Puglatizer doesn't replicate transformMixins:true as yet - or at least, I can't get it to transform mixins, only general Pug templates.

Should puglatizer be transforming mixins? If yes, how should I do it? If no, are you thinking of adding support for that option?

**Comment by happilymarrieddad** [comment]
Oh man I'm not really sure. I kind of wrote puglatizer and then didn't need it anymore because I use vue2 templates now. I'll take a look at it this weekend. Thanks!

**Comment by happilymarrieddad** [comment]
@cheshrkat Hey man, I haven't used Puglatizer in quite some time and I'm super busy so I don't think I'll be able to resolve this issue anytime soon. Please feel free to make a pull request and I will approve it. Sorry man. Thanks!

**Comment by cheshrkat** [comment]
@happilymarrieddad all good, thanks for letting me know :)

**Comment by og2t** [comment]
Support for mixins would be awesome 👍

**Comment by happilymarrieddad** [comment]
@og2t  Hey man, sorry I don't use puglatizer anymore. I more or less made it because someone on templatizer said it would be hilarious if someone made one for pug and bonus points for calling it puglatizer. I will accept a pull request though!
